insert into school (candidate_id, s_name, degree) values (456, 'etiam pretium iaculis justo', 'Professional');
insert into school (candidate_id, s_name, degree) values (536, 'at ipsum ac tellus', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (437, 'est', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (425, 'diam', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (640, 'lectus vestibulum quam', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (493, 'quam', 'Specialist');
insert into school (candidate_id, s_name, degree) values (557, 'dolor sit amet consectetuer', 'Graduate');
insert into school (candidate_id, s_name, degree) values (469, 'nunc nisl duis bibendum', 'Associate');
insert into school (candidate_id, s_name, degree) values (612, 'sit', 'Master');
insert into school (candidate_id, s_name, degree) values (360, 'nulla suspendisse potenti', 'Transfer');
insert into school (candidate_id, s_name, degree) values (541, 'ut rhoncus aliquet pulvinar', 'Specialist');
insert into school (candidate_id, s_name, degree) values (348, 'integer pede justo', 'Graduate');
insert into school (candidate_id, s_name, degree) values (448, 'tristique tortor eu pede', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (491, 'placerat praesent', 'Graduate');
insert into school (candidate_id, s_name, degree) values (454, 'in', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (453, 'donec', 'Associate');
insert into school (candidate_id, s_name, degree) values (455, 'condimentum', 'Associate');
insert into school (candidate_id, s_name, degree) values (405, 'sit amet nulla quisque', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (516, 'posuere', 'Transfer');
insert into school (candidate_id, s_name, degree) values (604, 'platea dictumst', 'Specialist');
insert into school (candidate_id, s_name, degree) values (385, 'pretium nisl', 'Transfer');
insert into school (candidate_id, s_name, degree) values (360, 'elementum ligula', 'Associate');
insert into school (candidate_id, s_name, degree) values (373, 'vel augue vestibulum rutrum', 'Professional');
insert into school (candidate_id, s_name, degree) values (612, 'fusce consequat', 'Specialist');
insert into school (candidate_id, s_name, degree) values (354, 'facilisi cras non velit', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (661, 'justo nec condimentum', 'Master');
insert into school (candidate_id, s_name, degree) values (354, 'lectus in quam', 'Specialist');
insert into school (candidate_id, s_name, degree) values (661, 'convallis nunc proin', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (454, 'ut suscipit', 'Master');
insert into school (candidate_id, s_name, degree) values (404, 'donec', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (611, 'ligula', 'Transfer');
insert into school (candidate_id, s_name, degree) values (394, 'primis', 'Master');
insert into school (candidate_id, s_name, degree) values (564, 'magna', 'Specialist');
insert into school (candidate_id, s_name, degree) values (573, 'ullamcorper augue', 'Master');
insert into school (candidate_id, s_name, degree) values (620, 'luctus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (539, 'vulputate nonummy maecenas tincidunt', 'Associate');
insert into school (candidate_id, s_name, degree) values (564, 'ac nibh', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (473, 'quis turpis', 'Specialist');
insert into school (candidate_id, s_name, degree) values (479, 'at velit eu', 'Associate');
insert into school (candidate_id, s_name, degree) values (579, 'eget', 'Specialist');
insert into school (candidate_id, s_name, degree) values (575, 'mus vivamus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (529, 'habitasse platea dictumst aliquam', 'Graduate');
insert into school (candidate_id, s_name, degree) values (478, 'orci', 'Master');
insert into school (candidate_id, s_name, degree) values (349, 'mattis odio', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (430, 'amet erat nulla', 'Transfer');
insert into school (candidate_id, s_name, degree) values (525, 'sit', 'Master');
insert into school (candidate_id, s_name, degree) values (337, 'morbi porttitor lorem', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (513, 'varius nulla facilisi', 'Graduate');
insert into school (candidate_id, s_name, degree) values (413, 'purus aliquet at feugiat', 'Associate');
insert into school (candidate_id, s_name, degree) values (361, 'praesent blandit lacinia', 'Transfer');
insert into school (candidate_id, s_name, degree) values (497, 'lectus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (490, 'cum sociis', 'Master');
insert into school (candidate_id, s_name, degree) values (601, 'dui vel', 'Specialist');
insert into school (candidate_id, s_name, degree) values (472, 'ut blandit non', 'Graduate');
insert into school (candidate_id, s_name, degree) values (584, 'nulla', 'Associate');
insert into school (candidate_id, s_name, degree) values (374, 'vestibulum ante ipsum', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (568, 'suspendisse', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (613, 'sit amet cursus', 'Specialist');
insert into school (candidate_id, s_name, degree) values (496, 'nulla neque', 'Graduate');
insert into school (candidate_id, s_name, degree) values (542, 'elit', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (632, 'nunc proin at', 'Specialist');
insert into school (candidate_id, s_name, degree) values (523, 'pellentesque ultrices', 'Associate');
insert into school (candidate_id, s_name, degree) values (470, 'in quam fringilla rhoncus', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (440, 'sapien dignissim vestibulum', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (506, 'mauris morbi non', 'Specialist');
insert into school (candidate_id, s_name, degree) values (574, 'non pretium quis lectus', 'Associate');
insert into school (candidate_id, s_name, degree) values (479, 'commodo', 'Professional');
insert into school (candidate_id, s_name, degree) values (412, 'cubilia curae', 'Graduate');
insert into school (candidate_id, s_name, degree) values (607, 'ultrices', 'Professional');
insert into school (candidate_id, s_name, degree) values (536, 'adipiscing lorem vitae mattis', 'Professional');
insert into school (candidate_id, s_name, degree) values (485, 'parturient', 'Master');
insert into school (candidate_id, s_name, degree) values (491, 'lorem id ligula suspendisse', 'Graduate');
insert into school (candidate_id, s_name, degree) values (407, 'nullam varius nulla facilisi', 'Transfer');
insert into school (candidate_id, s_name, degree) values (441, 'metus', 'Specialist');
insert into school (candidate_id, s_name, degree) values (577, 'mi nulla', 'Specialist');
insert into school (candidate_id, s_name, degree) values (354, 'arcu sed augue', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (579, 'in imperdiet et', 'Graduate');
insert into school (candidate_id, s_name, degree) values (540, 'aliquet massa', 'Graduate');
insert into school (candidate_id, s_name, degree) values (514, 'eleifend', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (363, 'ipsum primis in', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (443, 'platea dictumst', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (410, 'id mauris', 'Specialist');
insert into school (candidate_id, s_name, degree) values (484, 'turpis', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (612, 'nulla ac', 'Master');
insert into school (candidate_id, s_name, degree) values (629, 'pharetra magna vestibulum aliquet', 'Transfer');
insert into school (candidate_id, s_name, degree) values (420, 'sapien', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (609, 'mus vivamus vestibulum sagittis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (481, 'semper porta', 'Master');
insert into school (candidate_id, s_name, degree) values (492, 'pede ac diam cras', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (484, 'neque duis bibendum', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (375, 'non ligula pellentesque', 'Specialist');
insert into school (candidate_id, s_name, degree) values (473, 'quis augue luctus', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (645, 'tellus', 'Transfer');
insert into school (candidate_id, s_name, degree) values (434, 'suspendisse ornare', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (345, 'eleifend pede libero quis', 'Associate');
insert into school (candidate_id, s_name, degree) values (593, 'laoreet', 'Master');
insert into school (candidate_id, s_name, degree) values (589, 'augue', 'Associate');
insert into school (candidate_id, s_name, degree) values (603, 'sed justo pellentesque', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (486, 'nulla justo', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (439, 'enim in', 'Transfer');
insert into school (candidate_id, s_name, degree) values (379, 'hac habitasse', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (589, 'rhoncus dui vel', 'Graduate');
insert into school (candidate_id, s_name, degree) values (476, 'vulputate nonummy maecenas tincidunt', 'Master');
insert into school (candidate_id, s_name, degree) values (525, 'sem', 'Master');
insert into school (candidate_id, s_name, degree) values (483, 'nulla', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (385, 'turpis sed ante', 'Transfer');
insert into school (candidate_id, s_name, degree) values (499, 'massa', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (407, 'habitasse platea', 'Master');
insert into school (candidate_id, s_name, degree) values (434, 'id sapien', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (447, 'erat fermentum', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (395, 'magna vulputate luctus cum', 'Associate');
insert into school (candidate_id, s_name, degree) values (567, 'ante nulla justo', 'Master');
insert into school (candidate_id, s_name, degree) values (642, 'platea dictumst', 'Master');
insert into school (candidate_id, s_name, degree) values (360, 'ut', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (618, 'pede lobortis ligula sit', 'Master');
insert into school (candidate_id, s_name, degree) values (439, 'mauris', 'Graduate');
insert into school (candidate_id, s_name, degree) values (453, 'morbi a ipsum', 'Master');
insert into school (candidate_id, s_name, degree) values (633, 'quis tortor id', 'Master');
insert into school (candidate_id, s_name, degree) values (404, 'luctus cum sociis natoque', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (478, 'lacinia eget', 'Transfer');
insert into school (candidate_id, s_name, degree) values (465, 'eu', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (405, 'faucibus orci luctus', 'Specialist');
insert into school (candidate_id, s_name, degree) values (455, 'eget tincidunt eget tempus', 'Master');
insert into school (candidate_id, s_name, degree) values (507, 'nullam orci pede venenatis', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (662, 'diam cras pellentesque volutpat', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (515, 'in porttitor pede justo', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (408, 'proin interdum mauris non', 'Master');
insert into school (candidate_id, s_name, degree) values (387, 'aliquam erat', 'Specialist');
insert into school (candidate_id, s_name, degree) values (545, 'pede', 'Graduate');
insert into school (candidate_id, s_name, degree) values (504, 'magnis dis parturient montes', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (434, 'orci pede venenatis non', 'Graduate');
insert into school (candidate_id, s_name, degree) values (546, 'tempus', 'Professional');
insert into school (candidate_id, s_name, degree) values (371, 'ornare imperdiet sapien urna', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (570, 'id mauris', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (472, 'nam ultrices libero', 'Graduate');
insert into school (candidate_id, s_name, degree) values (387, 'sit', 'Transfer');
insert into school (candidate_id, s_name, degree) values (545, 'ultrices posuere cubilia curae', 'Specialist');
insert into school (candidate_id, s_name, degree) values (587, 'rutrum at', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (580, 'mattis nibh', 'Transfer');
insert into school (candidate_id, s_name, degree) values (407, 'consectetuer adipiscing', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (645, 'ultrices', 'Specialist');
insert into school (candidate_id, s_name, degree) values (554, 'mauris non ligula pellentesque', 'Transfer');
insert into school (candidate_id, s_name, degree) values (442, 'dapibus at', 'Associate');
insert into school (candidate_id, s_name, degree) values (478, 'faucibus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (640, 'sollicitudin mi', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (436, 'pretium nisl ut volutpat', 'Professional');
insert into school (candidate_id, s_name, degree) values (512, 'mauris', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (441, 'maecenas', 'Associate');
insert into school (candidate_id, s_name, degree) values (639, 'in hac habitasse platea', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (476, 'id ornare', 'Graduate');
insert into school (candidate_id, s_name, degree) values (375, 'aliquet massa id', 'Specialist');
insert into school (candidate_id, s_name, degree) values (417, 'morbi', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (356, 'tortor risus dapibus augue', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (365, 'est et tempus semper', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (557, 'nulla nisl nunc', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (418, 'maecenas', 'Master');
insert into school (candidate_id, s_name, degree) values (542, 'quam suspendisse potenti nullam', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (381, 'luctus et ultrices posuere', 'Transfer');
insert into school (candidate_id, s_name, degree) values (360, 'suspendisse', 'Master');
insert into school (candidate_id, s_name, degree) values (606, 'quis', 'Professional');
insert into school (candidate_id, s_name, degree) values (647, 'ultrices phasellus', 'Professional');
insert into school (candidate_id, s_name, degree) values (347, 'morbi vel lectus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (451, 'sem fusce', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (396, 'id pretium iaculis diam', 'Professional');
insert into school (candidate_id, s_name, degree) values (578, 'at nulla suspendisse potenti', 'Master');
insert into school (candidate_id, s_name, degree) values (452, 'sem praesent id', 'Transfer');
insert into school (candidate_id, s_name, degree) values (416, 'aliquet pulvinar', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (535, 'ultrices enim', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (428, 'integer pede', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (649, 'ipsum primis in', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (447, 'in congue etiam', 'Graduate');
insert into school (candidate_id, s_name, degree) values (485, 'condimentum id luctus nec', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (419, 'id', 'Associate');
insert into school (candidate_id, s_name, degree) values (621, 'in faucibus orci', 'Transfer');
insert into school (candidate_id, s_name, degree) values (422, 'massa', 'Associate');
insert into school (candidate_id, s_name, degree) values (490, 'sapien dignissim vestibulum vestibulum', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (490, 'nam congue', 'Master');
insert into school (candidate_id, s_name, degree) values (490, 'erat curabitur', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (595, 'mauris', 'Master');
insert into school (candidate_id, s_name, degree) values (367, 'habitasse platea dictumst', 'Professional');
insert into school (candidate_id, s_name, degree) values (568, 'in', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (522, 'eget tempus', 'Master');
insert into school (candidate_id, s_name, degree) values (511, 'velit donec diam neque', 'Associate');
insert into school (candidate_id, s_name, degree) values (569, 'in magna', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (539, 'tellus nulla', 'Transfer');
insert into school (candidate_id, s_name, degree) values (462, 'tristique', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (519, 'sapien placerat', 'Associate');
insert into school (candidate_id, s_name, degree) values (507, 'eget tempus vel', 'Master');
insert into school (candidate_id, s_name, degree) values (630, 'justo in blandit ultrices', 'Master');
insert into school (candidate_id, s_name, degree) values (390, 'amet', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (392, 'quis', 'Graduate');
insert into school (candidate_id, s_name, degree) values (500, 'vestibulum', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (414, 'amet nulla quisque arcu', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (409, 'sem duis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (381, 'eget orci vehicula condimentum', 'Specialist');
insert into school (candidate_id, s_name, degree) values (555, 'quam', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (611, 'eu nibh', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (491, 'augue aliquam', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (503, 'nec', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (425, 'donec odio', 'Specialist');
insert into school (candidate_id, s_name, degree) values (467, 'pede ac diam cras', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (619, 'ut tellus nulla ut', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (418, 'odio curabitur', 'Associate');
insert into school (candidate_id, s_name, degree) values (450, 'eros elementum', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (417, 'vestibulum quam sapien varius', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (399, 'faucibus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (643, 'maecenas', 'Master');
insert into school (candidate_id, s_name, degree) values (530, 'habitasse', 'Graduate');
insert into school (candidate_id, s_name, degree) values (398, 'ut rhoncus aliquet pulvinar', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (367, 'nulla tellus in', 'Professional');
insert into school (candidate_id, s_name, degree) values (466, 'sed', 'Master');
insert into school (candidate_id, s_name, degree) values (549, 'tincidunt lacus at', 'Graduate');
insert into school (candidate_id, s_name, degree) values (360, 'justo lacinia', 'Master');
insert into school (candidate_id, s_name, degree) values (517, 'etiam', 'Professional');
insert into school (candidate_id, s_name, degree) values (500, 'ullamcorper', 'Associate');
insert into school (candidate_id, s_name, degree) values (574, 'augue vestibulum', 'Specialist');
insert into school (candidate_id, s_name, degree) values (496, 'massa', 'Associate');
insert into school (candidate_id, s_name, degree) values (652, 'in', 'Professional');
insert into school (candidate_id, s_name, degree) values (542, 'accumsan tortor', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (657, 'eget semper rutrum nulla', 'Transfer');
insert into school (candidate_id, s_name, degree) values (394, 'quam turpis adipiscing lorem', 'Graduate');
insert into school (candidate_id, s_name, degree) values (471, 'tristique', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (458, 'luctus et ultrices', 'Transfer');
insert into school (candidate_id, s_name, degree) values (664, 'faucibus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (369, 'quam pharetra magna', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (460, 'tortor id nulla ultrices', 'Transfer');
insert into school (candidate_id, s_name, degree) values (348, 'posuere nonummy integer non', 'Transfer');
insert into school (candidate_id, s_name, degree) values (589, 'vestibulum', 'Specialist');
insert into school (candidate_id, s_name, degree) values (583, 'nisi', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (529, 'egestas metus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (620, 'felis fusce posuere', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (629, 'platea dictumst aliquam augue', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (418, 'amet justo', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (472, 'montes nascetur ridiculus mus', 'Specialist');
insert into school (candidate_id, s_name, degree) values (450, 'morbi sem mauris laoreet', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (423, 'aliquet massa id lobortis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (416, 'nam congue risus semper', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (487, 'ac tellus semper interdum', 'Graduate');
insert into school (candidate_id, s_name, degree) values (424, 'odio justo sollicitudin ut', 'Master');
insert into school (candidate_id, s_name, degree) values (644, 'elementum', 'Associate');
insert into school (candidate_id, s_name, degree) values (353, 'in faucibus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (643, 'eget', 'Associate');
insert into school (candidate_id, s_name, degree) values (563, 'aliquam sit amet', 'Associate');
insert into school (candidate_id, s_name, degree) values (473, 'lacus at', 'Specialist');
insert into school (candidate_id, s_name, degree) values (385, 'arcu libero rutrum', 'Graduate');
insert into school (candidate_id, s_name, degree) values (400, 'montes nascetur ridiculus mus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (356, 'euismod scelerisque', 'Associate');
insert into school (candidate_id, s_name, degree) values (615, 'amet sem', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (402, 'erat eros', 'Professional');
insert into school (candidate_id, s_name, degree) values (402, 'volutpat in congue etiam', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (404, 'bibendum imperdiet nullam orci', 'Professional');
insert into school (candidate_id, s_name, degree) values (556, 'magna', 'Professional');
insert into school (candidate_id, s_name, degree) values (498, 'aenean', 'Professional');
insert into school (candidate_id, s_name, degree) values (552, 'felis eu', 'Transfer');
insert into school (candidate_id, s_name, degree) values (479, 'semper interdum', 'Graduate');
insert into school (candidate_id, s_name, degree) values (449, 'nonummy maecenas tincidunt lacus', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (442, 'lectus pellentesque eget', 'Transfer');
insert into school (candidate_id, s_name, degree) values (460, 'massa', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (344, 'felis ut', 'Graduate');
insert into school (candidate_id, s_name, degree) values (346, 'malesuada', 'Transfer');
insert into school (candidate_id, s_name, degree) values (402, 'feugiat et', 'Master');
insert into school (candidate_id, s_name, degree) values (602, 'gravida', 'Graduate');
insert into school (candidate_id, s_name, degree) values (489, 'semper est', 'Specialist');
insert into school (candidate_id, s_name, degree) values (524, 'enim', 'Associate');
insert into school (candidate_id, s_name, degree) values (441, 'sed ante vivamus', 'Transfer');
insert into school (candidate_id, s_name, degree) values (628, 'libero nam', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (608, 'eget vulputate', 'Professional');
insert into school (candidate_id, s_name, degree) values (336, 'amet diam in', 'Transfer');
insert into school (candidate_id, s_name, degree) values (493, 'vestibulum', 'Specialist');
insert into school (candidate_id, s_name, degree) values (395, 'dui vel nisl duis', 'Specialist');
insert into school (candidate_id, s_name, degree) values (436, 'eleifend', 'Master');
insert into school (candidate_id, s_name, degree) values (639, 'dis parturient montes nascetur', 'Associate');
insert into school (candidate_id, s_name, degree) values (509, 'dapibus augue', 'Graduate');
insert into school (candidate_id, s_name, degree) values (664, 'habitasse platea dictumst', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (512, 'sit amet erat nulla', 'Professional');
insert into school (candidate_id, s_name, degree) values (395, 'orci luctus', 'Specialist');
insert into school (candidate_id, s_name, degree) values (594, 'vulputate justo in blandit', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (661, 'consectetuer adipiscing elit', 'Transfer');
insert into school (candidate_id, s_name, degree) values (450, 'cursus urna', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (614, 'in faucibus orci', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (523, 'est donec odio', 'Associate');
insert into school (candidate_id, s_name, degree) values (517, 'mi pede', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (497, 'congue elementum in hac', 'Master');
insert into school (candidate_id, s_name, degree) values (505, 'facilisi', 'Associate');
insert into school (candidate_id, s_name, degree) values (516, 'arcu sed augue', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (449, 'quisque arcu libero rutrum', 'Transfer');
insert into school (candidate_id, s_name, degree) values (492, 'platea dictumst aliquam', 'Master');
insert into school (candidate_id, s_name, degree) values (426, 'ultrices erat tortor', 'Associate');
insert into school (candidate_id, s_name, degree) values (557, 'consequat morbi a ipsum', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (410, 'faucibus', 'Master');
insert into school (candidate_id, s_name, degree) values (487, 'eget tempus vel pede', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (539, 'ipsum primis in', 'Master');
insert into school (candidate_id, s_name, degree) values (494, 'lectus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (608, 'sit amet cursus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (357, 'sit amet eros suspendisse', 'Specialist');
insert into school (candidate_id, s_name, degree) values (535, 'in faucibus orci luctus', 'Specialist');
insert into school (candidate_id, s_name, degree) values (525, 'in hac habitasse platea', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (570, 'ante vestibulum ante', 'Master');
insert into school (candidate_id, s_name, degree) values (341, 'venenatis tristique fusce', 'Transfer');
insert into school (candidate_id, s_name, degree) values (614, 'in ante', 'Associate');
insert into school (candidate_id, s_name, degree) values (403, 'pede', 'Transfer');
insert into school (candidate_id, s_name, degree) values (415, 'erat curabitur gravida', 'Master');
insert into school (candidate_id, s_name, degree) values (377, 'feugiat et eros vestibulum', 'Professional');
insert into school (candidate_id, s_name, degree) values (386, 'nascetur ridiculus mus', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (537, 'at vulputate', 'Master');
insert into school (candidate_id, s_name, degree) values (448, 'sit', 'Professional');
insert into school (candidate_id, s_name, degree) values (428, 'sagittis sapien cum', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (497, 'dapibus duis at', 'Specialist');
insert into school (candidate_id, s_name, degree) values (621, 'pede', 'Master');
insert into school (candidate_id, s_name, degree) values (582, 'turpis adipiscing lorem vitae', 'Specialist');
insert into school (candidate_id, s_name, degree) values (646, 'quisque', 'Transfer');
insert into school (candidate_id, s_name, degree) values (443, 'placerat ante nulla', 'Graduate');
insert into school (candidate_id, s_name, degree) values (439, 'augue', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (412, 'orci mauris lacinia', 'Associate');
insert into school (candidate_id, s_name, degree) values (561, 'congue eget', 'Transfer');
insert into school (candidate_id, s_name, degree) values (566, 'sapien cursus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (398, 'auctor sed', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (432, 'pellentesque eget', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (454, 'pede justo eu', 'Associate');
insert into school (candidate_id, s_name, degree) values (406, 'nulla facilisi', 'Master');
insert into school (candidate_id, s_name, degree) values (621, 'tortor sollicitudin mi sit', 'Master');
insert into school (candidate_id, s_name, degree) values (662, 'gravida', 'Professional');
insert into school (candidate_id, s_name, degree) values (577, 'id massa id nisl', 'Specialist');
insert into school (candidate_id, s_name, degree) values (359, 'suspendisse potenti nullam porttitor', 'Associate');
insert into school (candidate_id, s_name, degree) values (427, 'porta volutpat quam', 'Associate');
insert into school (candidate_id, s_name, degree) values (377, 'ultrices', 'Professional');
insert into school (candidate_id, s_name, degree) values (533, 'neque vestibulum eget vulputate', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (359, 'velit nec', 'Transfer');
insert into school (candidate_id, s_name, degree) values (516, 'nisi at nibh in', 'Specialist');
insert into school (candidate_id, s_name, degree) values (418, 'quam fringilla rhoncus', 'Master');
insert into school (candidate_id, s_name, degree) values (515, 'diam id ornare imperdiet', 'Graduate');
insert into school (candidate_id, s_name, degree) values (462, 'orci luctus', 'Associate');
insert into school (candidate_id, s_name, degree) values (604, 'est risus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (559, 'enim in tempor', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (616, 'mattis', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (560, 'orci luctus', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (641, 'eget nunc donec quis', 'Associate');
insert into school (candidate_id, s_name, degree) values (564, 'ligula', 'Associate');
insert into school (candidate_id, s_name, degree) values (473, 'diam id ornare', 'Professional');
insert into school (candidate_id, s_name, degree) values (371, 'dolor sit amet consectetuer', 'Specialist');
insert into school (candidate_id, s_name, degree) values (390, 'habitasse platea dictumst etiam', 'Specialist');
insert into school (candidate_id, s_name, degree) values (540, 'magnis', 'Specialist');
insert into school (candidate_id, s_name, degree) values (482, 'nulla ultrices aliquet maecenas', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (522, 'laoreet ut', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (346, 'accumsan felis ut at', 'Associate');
insert into school (candidate_id, s_name, degree) values (502, 'consequat lectus in', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (648, 'amet', 'Master');
insert into school (candidate_id, s_name, degree) values (452, 'primis', 'Associate');
insert into school (candidate_id, s_name, degree) values (365, 'eget elit sodales', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (470, 'feugiat', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (363, 'sagittis', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (500, 'dapibus dolor vel', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (417, 'posuere cubilia curae', 'Professional');
insert into school (candidate_id, s_name, degree) values (612, 'nibh fusce lacus', 'Specialist');
insert into school (candidate_id, s_name, degree) values (648, 'molestie hendrerit at', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (399, 'nibh ligula nec', 'Graduate');
insert into school (candidate_id, s_name, degree) values (625, 'suspendisse accumsan', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (652, 'nisl duis ac nibh', 'Specialist');
insert into school (candidate_id, s_name, degree) values (662, 'justo sollicitudin ut', 'Graduate');
insert into school (candidate_id, s_name, degree) values (622, 'enim in tempor turpis', 'Graduate');
insert into school (candidate_id, s_name, degree) values (609, 'in consequat ut nulla', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (451, 'congue diam', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (608, 'cras mi pede malesuada', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (624, 'velit nec nisi vulputate', 'Graduate');
insert into school (candidate_id, s_name, degree) values (532, 'cum sociis natoque penatibus', 'Specialist');
insert into school (candidate_id, s_name, degree) values (641, 'nulla elit ac nulla', 'Master');
insert into school (candidate_id, s_name, degree) values (363, 'ultricies eu nibh quisque', 'Associate');
insert into school (candidate_id, s_name, degree) values (384, 'ultrices enim lorem', 'Professional');
insert into school (candidate_id, s_name, degree) values (600, 'pellentesque ultrices phasellus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (492, 'volutpat dui maecenas tristique', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (641, 'vehicula condimentum curabitur', 'Transfer');
insert into school (candidate_id, s_name, degree) values (362, 'nonummy', 'Professional');
insert into school (candidate_id, s_name, degree) values (353, 'augue', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (628, 'volutpat in congue etiam', 'Graduate');
insert into school (candidate_id, s_name, degree) values (373, 'at ipsum ac', 'Specialist');
insert into school (candidate_id, s_name, degree) values (534, 'porta volutpat quam', 'Transfer');
insert into school (candidate_id, s_name, degree) values (391, 'nibh in hac habitasse', 'Transfer');
insert into school (candidate_id, s_name, degree) values (506, 'pede venenatis non', 'Associate');
insert into school (candidate_id, s_name, degree) values (530, 'condimentum curabitur in', 'Specialist');
insert into school (candidate_id, s_name, degree) values (421, 'magnis dis parturient', 'Master');
insert into school (candidate_id, s_name, degree) values (425, 'blandit ultrices', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (619, 'porta volutpat quam', 'Specialist');
insert into school (candidate_id, s_name, degree) values (610, 'vehicula condimentum', 'Graduate');
insert into school (candidate_id, s_name, degree) values (562, 'hac', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (465, 'quam a odio in', 'Specialist');
insert into school (candidate_id, s_name, degree) values (388, 'mauris vulputate elementum', 'Professional');
insert into school (candidate_id, s_name, degree) values (614, 'nulla neque libero', 'Master');
insert into school (candidate_id, s_name, degree) values (582, 'vitae quam', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (407, 'aenean auctor', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (352, 'tincidunt nulla mollis', 'Master');
insert into school (candidate_id, s_name, degree) values (471, 'at feugiat non', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (520, 'lorem', 'Graduate');
insert into school (candidate_id, s_name, degree) values (554, 'a feugiat et', 'Master');
insert into school (candidate_id, s_name, degree) values (448, 'porttitor id consequat in', 'Specialist');
insert into school (candidate_id, s_name, degree) values (641, 'ac nulla', 'Associate');
insert into school (candidate_id, s_name, degree) values (417, 'tempus vel pede', 'Associate');
insert into school (candidate_id, s_name, degree) values (479, 'tincidunt eget tempus vel', 'Transfer');
insert into school (candidate_id, s_name, degree) values (396, 'orci luctus et', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (609, 'mauris vulputate elementum', 'Master');
insert into school (candidate_id, s_name, degree) values (535, 'viverra dapibus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (505, 'ac lobortis', 'Master');
insert into school (candidate_id, s_name, degree) values (487, 'quis', 'Specialist');
insert into school (candidate_id, s_name, degree) values (394, 'sociis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (626, 'vestibulum', 'Professional');
insert into school (candidate_id, s_name, degree) values (585, 'nec condimentum neque', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (588, 'risus praesent lectus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (388, 'nunc', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (493, 'vestibulum ante ipsum primis', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (595, 'ac', 'Professional');
insert into school (candidate_id, s_name, degree) values (618, 'ante vel', 'Associate');
insert into school (candidate_id, s_name, degree) values (400, 'lorem ipsum', 'Transfer');
insert into school (candidate_id, s_name, degree) values (371, 'donec', 'Associate');
insert into school (candidate_id, s_name, degree) values (494, 'dapibus duis at', 'Graduate');
insert into school (candidate_id, s_name, degree) values (355, 'nisi eu orci mauris', 'Specialist');
insert into school (candidate_id, s_name, degree) values (335, 'ac diam cras', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (414, 'consequat morbi', 'Master');
insert into school (candidate_id, s_name, degree) values (646, 'nec dui luctus rutrum', 'Associate');
insert into school (candidate_id, s_name, degree) values (426, 'erat quisque', 'Associate');
insert into school (candidate_id, s_name, degree) values (434, 'eget', 'Master');
insert into school (candidate_id, s_name, degree) values (531, 'eu est congue', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (649, 'urna ut', 'Associate');
insert into school (candidate_id, s_name, degree) values (634, 'non mattis', 'Master');
insert into school (candidate_id, s_name, degree) values (648, 'tellus nulla', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (428, 'dui', 'Associate');
insert into school (candidate_id, s_name, degree) values (462, 'libero convallis eget eleifend', 'Master');
insert into school (candidate_id, s_name, degree) values (639, 'consequat nulla nisl nunc', 'Graduate');
insert into school (candidate_id, s_name, degree) values (610, 'et', 'Transfer');
insert into school (candidate_id, s_name, degree) values (486, 'duis aliquam convallis nunc', 'Specialist');
insert into school (candidate_id, s_name, degree) values (574, 'vehicula consequat morbi a', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (335, 'aliquet massa id lobortis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (437, 'lacinia', 'Transfer');
insert into school (candidate_id, s_name, degree) values (425, 'accumsan odio curabitur', 'Master');
insert into school (candidate_id, s_name, degree) values (428, 'condimentum curabitur', 'Specialist');
insert into school (candidate_id, s_name, degree) values (553, 'pretium iaculis diam', 'Master');
insert into school (candidate_id, s_name, degree) values (381, 'massa quis augue', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (657, 'pede', 'Associate');
insert into school (candidate_id, s_name, degree) values (395, 'tempus vel pede morbi', 'Specialist');
insert into school (candidate_id, s_name, degree) values (595, 'platea', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (601, 'nec nisi', 'Graduate');
insert into school (candidate_id, s_name, degree) values (597, 'praesent', 'Associate');
insert into school (candidate_id, s_name, degree) values (530, 'proin leo odio', 'Graduate');
insert into school (candidate_id, s_name, degree) values (434, 'sed interdum', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (403, 'quis augue luctus', 'Master');
insert into school (candidate_id, s_name, degree) values (528, 'vulputate ut ultrices', 'Transfer');
insert into school (candidate_id, s_name, degree) values (618, 'leo odio', 'Associate');
insert into school (candidate_id, s_name, degree) values (601, 'et magnis dis', 'Specialist');
insert into school (candidate_id, s_name, degree) values (388, 'tempor turpis nec euismod', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (509, 'consequat', 'Transfer');
insert into school (candidate_id, s_name, degree) values (540, 'morbi sem mauris laoreet', 'Transfer');
insert into school (candidate_id, s_name, degree) values (385, 'cubilia curae nulla dapibus', 'Professional');
insert into school (candidate_id, s_name, degree) values (499, 'augue vestibulum', 'Associate');
insert into school (candidate_id, s_name, degree) values (591, 'ut', 'Transfer');
insert into school (candidate_id, s_name, degree) values (504, 'proin', 'Master');
insert into school (candidate_id, s_name, degree) values (543, 'donec ut mauris', 'Associate');
insert into school (candidate_id, s_name, degree) values (427, 'vel enim sit', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (600, 'libero nullam', 'Master');
insert into school (candidate_id, s_name, degree) values (433, 'pretium iaculis diam erat', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (445, 'ac', 'Associate');
insert into school (candidate_id, s_name, degree) values (424, 'imperdiet et commodo vulputate', 'Associate');
insert into school (candidate_id, s_name, degree) values (490, 'a', 'Transfer');
insert into school (candidate_id, s_name, degree) values (619, 'nulla', 'Associate');
insert into school (candidate_id, s_name, degree) values (635, 'est risus auctor', 'Master');
insert into school (candidate_id, s_name, degree) values (551, 'pulvinar lobortis', 'Professional');
insert into school (candidate_id, s_name, degree) values (445, 'mauris vulputate elementum nullam', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (461, 'sodales sed tincidunt', 'Associate');
insert into school (candidate_id, s_name, degree) values (632, 'sit amet justo', 'Graduate');
insert into school (candidate_id, s_name, degree) values (501, 'lectus suspendisse potenti', 'Graduate');
insert into school (candidate_id, s_name, degree) values (594, 'lectus pellentesque', 'Transfer');
insert into school (candidate_id, s_name, degree) values (455, 'in', 'Graduate');
insert into school (candidate_id, s_name, degree) values (548, 'sed sagittis', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (577, 'nullam sit amet turpis', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (562, 'fermentum justo nec condimentum', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (478, 'eleifend', 'Specialist');
insert into school (candidate_id, s_name, degree) values (436, 'amet nulla', 'Master');
insert into school (candidate_id, s_name, degree) values (513, 'dapibus augue vel', 'Master');
insert into school (candidate_id, s_name, degree) values (619, 'dapibus duis', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (520, 'dolor morbi vel lectus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (587, 'libero', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (615, 'nulla eget', 'Transfer');
insert into school (candidate_id, s_name, degree) values (666, 'massa', 'Specialist');
insert into school (candidate_id, s_name, degree) values (565, 'ligula', 'Transfer');
insert into school (candidate_id, s_name, degree) values (534, 'in porttitor pede justo', 'Associate');
insert into school (candidate_id, s_name, degree) values (642, 'et commodo vulputate justo', 'Specialist');
insert into school (candidate_id, s_name, degree) values (635, 'non sodales', 'Associate');
insert into school (candidate_id, s_name, degree) values (399, 'scelerisque', 'Master');
insert into school (candidate_id, s_name, degree) values (459, 'maecenas', 'Specialist');
insert into school (candidate_id, s_name, degree) values (634, 'donec vitae nisi', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (488, 'potenti', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (517, 'id ornare imperdiet sapien', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (428, 'turpis', 'Specialist');
insert into school (candidate_id, s_name, degree) values (620, 'eget orci vehicula condimentum', 'Graduate');
insert into school (candidate_id, s_name, degree) values (350, 'leo pellentesque ultrices', 'Professional');
insert into school (candidate_id, s_name, degree) values (418, 'morbi a', 'Associate');
insert into school (candidate_id, s_name, degree) values (655, 'consectetuer', 'Transfer');
insert into school (candidate_id, s_name, degree) values (556, 'sem praesent id', 'Professional');
insert into school (candidate_id, s_name, degree) values (658, 'auctor sed tristique', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (613, 'venenatis tristique fusce', 'Graduate');
insert into school (candidate_id, s_name, degree) values (493, 'nibh ligula nec sem', 'Associate');
insert into school (candidate_id, s_name, degree) values (373, 'sem praesent', 'Associate');
insert into school (candidate_id, s_name, degree) values (523, 'amet turpis elementum ligula', 'Specialist');
insert into school (candidate_id, s_name, degree) values (558, 'interdum mauris ullamcorper', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (415, 'volutpat', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (610, 'erat eros viverra', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (625, 'sit amet turpis', 'Professional');
insert into school (candidate_id, s_name, degree) values (606, 'mauris viverra', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (495, 'lobortis sapien', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (359, 'augue vestibulum rutrum rutrum', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (409, 'metus', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (525, 'cursus vestibulum proin eu', 'Associate');
insert into school (candidate_id, s_name, degree) values (635, 'ultrices posuere cubilia curae', 'Specialist');
insert into school (candidate_id, s_name, degree) values (516, 'diam nam tristique tortor', 'Professional');
insert into school (candidate_id, s_name, degree) values (641, 'semper porta volutpat quam', 'Professional');
insert into school (candidate_id, s_name, degree) values (371, 'quis orci', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (627, 'nulla sed accumsan', 'Master');
insert into school (candidate_id, s_name, degree) values (593, 'ante nulla', 'Transfer');
insert into school (candidate_id, s_name, degree) values (392, 'quam suspendisse potenti nullam', 'Professional');
insert into school (candidate_id, s_name, degree) values (382, 'nisi nam ultrices', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (604, 'donec pharetra', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (413, 'id', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (506, 'cursus urna ut tellus', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (525, 'ut', 'Transfer');
insert into school (candidate_id, s_name, degree) values (378, 'habitasse', 'Master');
insert into school (candidate_id, s_name, degree) values (654, 'vel', 'Professional');
insert into school (candidate_id, s_name, degree) values (665, 'diam vitae', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (504, 'tempor', 'Graduate');
insert into school (candidate_id, s_name, degree) values (495, 'libero ut', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (390, 'sed ante', 'Transfer');
insert into school (candidate_id, s_name, degree) values (664, 'non interdum', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (392, 'turpis', 'Master');
insert into school (candidate_id, s_name, degree) values (573, 'ut', 'Specialist');
insert into school (candidate_id, s_name, degree) values (372, 'vehicula', 'Professional');
insert into school (candidate_id, s_name, degree) values (558, 'ultrices phasellus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (560, 'lacus at velit', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (527, 'aliquam erat volutpat', 'Specialist');
insert into school (candidate_id, s_name, degree) values (656, 'porttitor lacus at turpis', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (368, 'nisl', 'Associate');
insert into school (candidate_id, s_name, degree) values (408, 'posuere cubilia curae nulla', 'Professional');
insert into school (candidate_id, s_name, degree) values (528, 'nisi eu orci mauris', 'Master');
insert into school (candidate_id, s_name, degree) values (392, 'at nunc commodo placerat', 'Master');
insert into school (candidate_id, s_name, degree) values (335, 'justo etiam pretium iaculis', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (417, 'lacus', 'Transfer');
insert into school (candidate_id, s_name, degree) values (381, 'adipiscing molestie hendrerit at', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (384, 'libero non mattis', 'Graduate');
insert into school (candidate_id, s_name, degree) values (415, 'elit', 'Professional');
insert into school (candidate_id, s_name, degree) values (589, 'duis at velit eu', 'Master');
insert into school (candidate_id, s_name, degree) values (511, 'curabitur gravida nisi at', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (487, 'in', 'Associate');
insert into school (candidate_id, s_name, degree) values (400, 'at ipsum ac', 'Associate');
insert into school (candidate_id, s_name, degree) values (441, 'erat nulla tempus vivamus', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (447, 'neque duis', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (593, 'vehicula consequat morbi', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (482, 'nisl', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (487, 'ut mauris', 'Associate');
insert into school (candidate_id, s_name, degree) values (573, 'quam a odio', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (351, 'tortor sollicitudin mi', 'Specialist');
insert into school (candidate_id, s_name, degree) values (440, 'in sagittis dui vel', 'Master');
insert into school (candidate_id, s_name, degree) values (644, 'sociis natoque penatibus', 'Transfer');
insert into school (candidate_id, s_name, degree) values (449, 'convallis nunc proin at', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (560, 'mauris morbi', 'Transfer');
insert into school (candidate_id, s_name, degree) values (479, 'augue', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (618, 'vehicula condimentum', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (544, 'dignissim vestibulum vestibulum ante', 'Graduate');
insert into school (candidate_id, s_name, degree) values (404, 'faucibus', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (353, 'pede', 'Professional');
insert into school (candidate_id, s_name, degree) values (620, 'nulla suscipit ligula in', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (346, 'vestibulum', 'Specialist');
insert into school (candidate_id, s_name, degree) values (361, 'in hac', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (334, 'in', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (337, 'neque', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (509, 'pellentesque eget nunc donec', 'Graduate');
insert into school (candidate_id, s_name, degree) values (462, 'tincidunt lacus at velit', 'Graduate');
insert into school (candidate_id, s_name, degree) values (598, 'sapien sapien non', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (514, 'ante vivamus', 'Associate');
insert into school (candidate_id, s_name, degree) values (662, 'vel', 'Specialist');
insert into school (candidate_id, s_name, degree) values (438, 'eleifend luctus', 'Associate');
insert into school (candidate_id, s_name, degree) values (484, 'ipsum primis in', 'Graduate');
insert into school (candidate_id, s_name, degree) values (572, 'commodo placerat praesent blandit', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (374, 'nulla quisque', 'Specialist');
insert into school (candidate_id, s_name, degree) values (595, 'orci pede', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (377, 'sapien dignissim vestibulum vestibulum', 'Master');
insert into school (candidate_id, s_name, degree) values (635, 'blandit mi in', 'Master');
insert into school (candidate_id, s_name, degree) values (339, 'parturient montes nascetur ridiculus', 'Master');
insert into school (candidate_id, s_name, degree) values (620, 'sed nisl nunc', 'Specialist');
insert into school (candidate_id, s_name, degree) values (434, 'nibh in quis justo', 'Professional');
insert into school (candidate_id, s_name, degree) values (356, 'sed', 'Transfer');
insert into school (candidate_id, s_name, degree) values (537, 'praesent blandit nam', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (502, 'elementum ligula vehicula', 'Associate');
insert into school (candidate_id, s_name, degree) values (363, 'tortor risus', 'Master');
insert into school (candidate_id, s_name, degree) values (563, 'ut nulla', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (551, 'habitasse platea', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (403, 'nascetur ridiculus mus', 'Master');
insert into school (candidate_id, s_name, degree) values (490, 'sed sagittis', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (387, 'egestas', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (359, 'mauris enim leo rhoncus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (617, 'semper rutrum nulla', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (624, 'ligula suspendisse ornare consequat', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (458, 'in tempor turpis', 'Graduate');
insert into school (candidate_id, s_name, degree) values (575, 'lobortis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (399, 'parturient montes nascetur ridiculus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (605, 'sed interdum', 'Specialist');
insert into school (candidate_id, s_name, degree) values (652, 'vulputate luctus', 'Transfer');
insert into school (candidate_id, s_name, degree) values (393, 'cras in purus eu', 'Associate');
insert into school (candidate_id, s_name, degree) values (563, 'et', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (452, 'pellentesque at', 'Master');
insert into school (candidate_id, s_name, degree) values (433, 'nulla', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (487, 'metus', 'Specialist');
insert into school (candidate_id, s_name, degree) values (603, 'sollicitudin ut suscipit a', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (486, 'dui nec', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (513, 'sit amet', 'Graduate');
insert into school (candidate_id, s_name, degree) values (613, 'elit proin risus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (628, 'donec', 'Specialist');
insert into school (candidate_id, s_name, degree) values (355, 'sodales', 'Professional');
insert into school (candidate_id, s_name, degree) values (467, 'congue eget semper', 'Master');
insert into school (candidate_id, s_name, degree) values (341, 'potenti in eleifend quam', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (549, 'vulputate ut ultrices vel', 'Transfer');
insert into school (candidate_id, s_name, degree) values (538, 'non', 'Specialist');
insert into school (candidate_id, s_name, degree) values (383, 'quis justo maecenas', 'Transfer');
insert into school (candidate_id, s_name, degree) values (442, 'et commodo', 'Associate');
insert into school (candidate_id, s_name, degree) values (572, 'praesent lectus', 'Associate');
insert into school (candidate_id, s_name, degree) values (427, 'aenean', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (381, 'nulla justo aliquam', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (595, 'turpis sed ante', 'Master');
insert into school (candidate_id, s_name, degree) values (557, 'tristique', 'Transfer');
insert into school (candidate_id, s_name, degree) values (419, 'luctus nec', 'Graduate');
insert into school (candidate_id, s_name, degree) values (457, 'venenatis turpis enim blandit', 'Associate');
insert into school (candidate_id, s_name, degree) values (575, 'quis augue', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (547, 'tempus semper est quam', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (617, 'proin at', 'Specialist');
insert into school (candidate_id, s_name, degree) values (387, 'ac', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (533, 'libero nam dui proin', 'Associate');
insert into school (candidate_id, s_name, degree) values (339, 'felis', 'Graduate');
insert into school (candidate_id, s_name, degree) values (464, 'purus', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (525, 'pellentesque quisque porta volutpat', 'Associate');
insert into school (candidate_id, s_name, degree) values (353, 'erat tortor', 'Associate');
insert into school (candidate_id, s_name, degree) values (431, 'erat', 'Associate');
insert into school (candidate_id, s_name, degree) values (650, 'sagittis', 'Specialist');
insert into school (candidate_id, s_name, degree) values (363, 'eros suspendisse', 'Professional');
insert into school (candidate_id, s_name, degree) values (449, 'donec vitae nisi nam', 'Professional');
insert into school (candidate_id, s_name, degree) values (373, 'laoreet', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (421, 'urna pretium', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (396, 'blandit ultrices enim lorem', 'Specialist');
insert into school (candidate_id, s_name, degree) values (521, 'fusce', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (354, 'elit sodales', 'Master');
insert into school (candidate_id, s_name, degree) values (421, 'primis', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (563, 'pellentesque ultrices mattis odio', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (574, 'amet', 'Graduate');
insert into school (candidate_id, s_name, degree) values (609, 'sollicitudin vitae consectetuer eget', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (395, 'quis orci eget orci', 'Specialist');
insert into school (candidate_id, s_name, degree) values (516, 'orci', 'Professional');
insert into school (candidate_id, s_name, degree) values (393, 'libero quis orci', 'Master');
insert into school (candidate_id, s_name, degree) values (371, 'libero nam', 'Master');
insert into school (candidate_id, s_name, degree) values (544, 'rutrum ac', 'Master');
insert into school (candidate_id, s_name, degree) values (558, 'neque vestibulum eget vulputate', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (435, 'faucibus orci luctus et', 'Professional');
insert into school (candidate_id, s_name, degree) values (656, 'eget vulputate', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (578, 'sit amet lobortis sapien', 'Transfer');
insert into school (candidate_id, s_name, degree) values (528, 'massa', 'Professional');
insert into school (candidate_id, s_name, degree) values (548, 'augue quam sollicitudin', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (339, 'dictumst', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (543, 'ac', 'Specialist');
insert into school (candidate_id, s_name, degree) values (627, 'euismod', 'Transfer');
insert into school (candidate_id, s_name, degree) values (352, 'montes nascetur', 'Professional');
insert into school (candidate_id, s_name, degree) values (339, 'posuere cubilia curae', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (635, 'vestibulum', 'Graduate');
insert into school (candidate_id, s_name, degree) values (586, 'in quam fringilla', 'Associate');
insert into school (candidate_id, s_name, degree) values (545, 'ligula suspendisse ornare consequat', 'Graduate');
insert into school (candidate_id, s_name, degree) values (423, 'erat eros viverra', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (609, 'vivamus vestibulum', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (478, 'accumsan odio', 'Associate');
insert into school (candidate_id, s_name, degree) values (649, 'in felis', 'Graduate');
insert into school (candidate_id, s_name, degree) values (453, 'orci mauris lacinia sapien', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (642, 'est', 'Specialist');
insert into school (candidate_id, s_name, degree) values (487, 'at velit eu', 'Master');
insert into school (candidate_id, s_name, degree) values (551, 'molestie hendrerit at vulputate', 'Associate');
insert into school (candidate_id, s_name, degree) values (340, 'amet sem', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (366, 'turpis enim', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (500, 'et magnis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (454, 'phasellus id', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (521, 'eget', 'Associate');
insert into school (candidate_id, s_name, degree) values (663, 'ligula sit amet eleifend', 'Specialist');
insert into school (candidate_id, s_name, degree) values (500, 'est risus auctor sed', 'Specialist');
insert into school (candidate_id, s_name, degree) values (561, 'elementum pellentesque', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (477, 'lobortis est phasellus sit', 'Associate');
insert into school (candidate_id, s_name, degree) values (655, 'a', 'Associate');
insert into school (candidate_id, s_name, degree) values (495, 'a', 'Transfer');
insert into school (candidate_id, s_name, degree) values (635, 'erat', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (659, 'in blandit ultrices enim', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (428, 'amet cursus id turpis', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (586, 'nunc commodo placerat', 'Professional');
insert into school (candidate_id, s_name, degree) values (406, 'nam ultrices libero non', 'Transfer');
insert into school (candidate_id, s_name, degree) values (665, 'aliquam quis turpis', 'Master');
insert into school (candidate_id, s_name, degree) values (597, 'sit', 'Master');
insert into school (candidate_id, s_name, degree) values (423, 'nunc commodo placerat', 'Professional');
insert into school (candidate_id, s_name, degree) values (536, 'iaculis', 'Professional');
insert into school (candidate_id, s_name, degree) values (641, 'eu', 'Graduate');
insert into school (candidate_id, s_name, degree) values (511, 'lectus suspendisse potenti in', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (355, 'quisque erat', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (454, 'vel pede morbi porttitor', 'Transfer');
insert into school (candidate_id, s_name, degree) values (634, 'augue aliquam', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (337, 'ultrices', 'Professional');
insert into school (candidate_id, s_name, degree) values (339, 'amet nunc viverra', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (416, 'sapien urna', 'Transfer');
insert into school (candidate_id, s_name, degree) values (419, 'tristique tortor eu pede', 'Transfer');
insert into school (candidate_id, s_name, degree) values (377, 'eget', 'Graduate');
insert into school (candidate_id, s_name, degree) values (559, 'aliquam quis turpis', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (597, 'luctus nec molestie sed', 'Professional');
insert into school (candidate_id, s_name, degree) values (508, 'mauris sit amet eros', 'Transfer');
insert into school (candidate_id, s_name, degree) values (661, 'mi pede malesuada in', 'Specialist');
insert into school (candidate_id, s_name, degree) values (375, 'curae', 'Graduate');
insert into school (candidate_id, s_name, degree) values (621, 'ut erat id', 'Specialist');
insert into school (candidate_id, s_name, degree) values (378, 'eleifend', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (542, 'amet', 'Professional');
insert into school (candidate_id, s_name, degree) values (479, 'pellentesque ultrices', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (365, 'eu est', 'Specialist');
insert into school (candidate_id, s_name, degree) values (363, 'aliquam convallis', 'Specialist');
insert into school (candidate_id, s_name, degree) values (514, 'dictumst morbi vestibulum', 'Master');
insert into school (candidate_id, s_name, degree) values (592, 'vel lectus in', 'Master');
insert into school (candidate_id, s_name, degree) values (553, 'donec semper sapien', 'Transfer');
insert into school (candidate_id, s_name, degree) values (339, 'interdum', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (633, 'metus sapien ut nunc', 'Graduate');
insert into school (candidate_id, s_name, degree) values (344, 'est quam pharetra magna', 'Transfer');
insert into school (candidate_id, s_name, degree) values (446, 'aliquam', 'Transfer');
insert into school (candidate_id, s_name, degree) values (570, 'blandit', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (523, 'primis in faucibus orci', 'Professional');
insert into school (candidate_id, s_name, degree) values (420, 'rutrum ac', 'Graduate');
insert into school (candidate_id, s_name, degree) values (420, 'suspendisse ornare', 'Graduate');
insert into school (candidate_id, s_name, degree) values (370, 'ac consequat metus', 'Professional');
insert into school (candidate_id, s_name, degree) values (405, 'orci mauris', 'Transfer');
insert into school (candidate_id, s_name, degree) values (465, 'in', 'Associate');
insert into school (candidate_id, s_name, degree) values (390, 'phasellus id sapien in', 'Specialist');
insert into school (candidate_id, s_name, degree) values (335, 'enim', 'Specialist');
insert into school (candidate_id, s_name, degree) values (565, 'felis ut', 'Transfer');
insert into school (candidate_id, s_name, degree) values (359, 'libero non mattis pulvinar', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (437, 'nulla suscipit ligula in', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (567, 'orci mauris lacinia sapien', 'Master');
insert into school (candidate_id, s_name, degree) values (599, 'vitae mattis nibh', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (451, 'convallis', 'Associate');
insert into school (candidate_id, s_name, degree) values (551, 'rhoncus aliquet pulvinar sed', 'Associate');
insert into school (candidate_id, s_name, degree) values (618, 'phasellus in', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (452, 'tristique in', 'Master');
insert into school (candidate_id, s_name, degree) values (424, 'mauris vulputate elementum nullam', 'Specialist');
insert into school (candidate_id, s_name, degree) values (460, 'leo', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (647, 'posuere cubilia curae', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (493, 'sapien in sapien', 'Master');
insert into school (candidate_id, s_name, degree) values (518, 'tincidunt ante vel ipsum', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (379, 'enim lorem', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (661, 'in faucibus orci luctus', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (368, 'porttitor pede', 'Transfer');
insert into school (candidate_id, s_name, degree) values (523, 'risus', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (588, 'nibh ligula nec sem', 'Associate');
insert into school (candidate_id, s_name, degree) values (397, 'aenean', 'Associate');
insert into school (candidate_id, s_name, degree) values (553, 'velit', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (558, 'habitasse platea dictumst', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (513, 'at turpis donec posuere', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (402, 'ut massa volutpat convallis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (339, 'sed tristique', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (406, 'aliquet massa id', 'Graduate');
insert into school (candidate_id, s_name, degree) values (412, 'lectus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (495, 'est congue elementum', 'Transfer');
insert into school (candidate_id, s_name, degree) values (380, 'iaculis diam', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (504, 'morbi quis tortor id', 'Specialist');
insert into school (candidate_id, s_name, degree) values (373, 'platea dictumst maecenas ut', 'Master');
insert into school (candidate_id, s_name, degree) values (632, 'mollis molestie', 'Master');
insert into school (candidate_id, s_name, degree) values (536, 'nulla ultrices aliquet maecenas', 'Graduate');
insert into school (candidate_id, s_name, degree) values (502, 'quis orci nullam', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (495, 'ut at', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (469, 'justo sollicitudin', 'Professional');
insert into school (candidate_id, s_name, degree) values (603, 'in', 'Transfer');
insert into school (candidate_id, s_name, degree) values (463, 'cubilia', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (619, 'eget eleifend luctus ultricies', 'Professional');
insert into school (candidate_id, s_name, degree) values (429, 'sed sagittis nam', 'Graduate');
insert into school (candidate_id, s_name, degree) values (456, 'eget orci vehicula', 'Transfer');
insert into school (candidate_id, s_name, degree) values (587, 'nulla dapibus', 'Transfer');
insert into school (candidate_id, s_name, degree) values (580, 'sit amet justo', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (581, 'suspendisse ornare consequat lectus', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (397, 'felis fusce', 'Professional');
insert into school (candidate_id, s_name, degree) values (583, 'nullam', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (432, 'tincidunt', 'Transfer');
insert into school (candidate_id, s_name, degree) values (631, 'justo morbi', 'Master');
insert into school (candidate_id, s_name, degree) values (464, 'neque', 'Specialist');
insert into school (candidate_id, s_name, degree) values (521, 'luctus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (615, 'porttitor id', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (607, 'feugiat non', 'Transfer');
insert into school (candidate_id, s_name, degree) values (656, 'consequat lectus in', 'Transfer');
insert into school (candidate_id, s_name, degree) values (476, 'odio porttitor id consequat', 'Master');
insert into school (candidate_id, s_name, degree) values (588, 'sem fusce consequat nulla', 'Graduate');
insert into school (candidate_id, s_name, degree) values (377, 'penatibus et magnis dis', 'Professional');
insert into school (candidate_id, s_name, degree) values (382, 'sed justo pellentesque', 'Specialist');
insert into school (candidate_id, s_name, degree) values (428, 'erat volutpat in', 'Transfer');
insert into school (candidate_id, s_name, degree) values (535, 'nullam molestie', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (432, 'orci mauris lacinia sapien', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (337, 'orci pede venenatis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (554, 'malesuada', 'Master');
insert into school (candidate_id, s_name, degree) values (581, 'nulla justo aliquam', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (612, 'odio consequat', 'Graduate');
insert into school (candidate_id, s_name, degree) values (465, 'consequat', 'Associate');
insert into school (candidate_id, s_name, degree) values (649, 'id', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (552, 'cubilia curae', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (446, 'pulvinar sed', 'Specialist');
insert into school (candidate_id, s_name, degree) values (608, 'donec', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (584, 'vel augue', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (600, 'pede posuere', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (357, 'orci', 'Transfer');
insert into school (candidate_id, s_name, degree) values (435, 'pellentesque ultrices', 'Master');
insert into school (candidate_id, s_name, degree) values (572, 'est', 'Transfer');
insert into school (candidate_id, s_name, degree) values (548, 'etiam vel augue', 'Transfer');
insert into school (candidate_id, s_name, degree) values (599, 'sit amet lobortis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (527, 'porttitor lorem id', 'Associate');
insert into school (candidate_id, s_name, degree) values (620, 'in consequat', 'Transfer');
insert into school (candidate_id, s_name, degree) values (542, 'ut mauris', 'Transfer');
insert into school (candidate_id, s_name, degree) values (616, 'in purus', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (472, 'neque', 'Professional');
insert into school (candidate_id, s_name, degree) values (445, 'vivamus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (624, 'diam', 'Graduate');
insert into school (candidate_id, s_name, degree) values (599, 'amet turpis elementum', 'Master');
insert into school (candidate_id, s_name, degree) values (589, 'nisi at', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (374, 'vel pede', 'Transfer');
insert into school (candidate_id, s_name, degree) values (623, 'aliquam erat volutpat in', 'Transfer');
insert into school (candidate_id, s_name, degree) values (565, 'nisi nam ultrices libero', 'Graduate');
insert into school (candidate_id, s_name, degree) values (529, 'non interdum in', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (546, 'nunc proin at turpis', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (559, 'nulla', 'Professional');
insert into school (candidate_id, s_name, degree) values (560, 'ut odio cras mi', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (381, 'nec sem', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (573, 'in', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (436, 'integer ac', 'Professional');
insert into school (candidate_id, s_name, degree) values (540, 'ut rhoncus aliquet pulvinar', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (342, 'lobortis', 'Professional');
insert into school (candidate_id, s_name, degree) values (456, 'nonummy integer non velit', 'Associate');
insert into school (candidate_id, s_name, degree) values (631, 'quam sollicitudin vitae consectetuer', 'Professional');
insert into school (candidate_id, s_name, degree) values (395, 'elit sodales', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (417, 'augue', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (495, 'non velit donec', 'Associate');
insert into school (candidate_id, s_name, degree) values (619, 'primis in faucibus orci', 'Graduate');
insert into school (candidate_id, s_name, degree) values (493, 'ac', 'Transfer');
insert into school (candidate_id, s_name, degree) values (527, 'ullamcorper purus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (485, 'cubilia', 'Associate');
insert into school (candidate_id, s_name, degree) values (396, 'ipsum primis in faucibus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (477, 'risus', 'Professional');
insert into school (candidate_id, s_name, degree) values (512, 'integer ac', 'Professional');
insert into school (candidate_id, s_name, degree) values (436, 'purus phasellus in', 'Associate');
insert into school (candidate_id, s_name, degree) values (406, 'in leo maecenas', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (623, 'morbi quis tortor id', 'Transfer');
insert into school (candidate_id, s_name, degree) values (418, 'mus vivamus', 'Specialist');
insert into school (candidate_id, s_name, degree) values (379, 'arcu adipiscing', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (352, 'id turpis integer aliquet', 'Professional');
insert into school (candidate_id, s_name, degree) values (639, 'ut nunc', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (546, 'odio', 'Graduate');
insert into school (candidate_id, s_name, degree) values (602, 'sed magna at', 'Associate');
insert into school (candidate_id, s_name, degree) values (405, 'cubilia', 'Specialist');
insert into school (candidate_id, s_name, degree) values (336, 'ultrices posuere', 'Graduate');
insert into school (candidate_id, s_name, degree) values (500, 'rhoncus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (340, 'felis ut at dolor', 'Transfer');
insert into school (candidate_id, s_name, degree) values (585, 'parturient montes nascetur', 'Graduate');
insert into school (candidate_id, s_name, degree) values (398, 'dui proin leo odio', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (362, 'amet eleifend pede libero', 'Specialist');
insert into school (candidate_id, s_name, degree) values (476, 'in', 'Specialist');
insert into school (candidate_id, s_name, degree) values (543, 'aliquam erat volutpat in', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (436, 'justo aliquam', 'Specialist');
insert into school (candidate_id, s_name, degree) values (345, 'ut tellus nulla ut', 'Transfer');
insert into school (candidate_id, s_name, degree) values (471, 'porttitor pede justo', 'Professional');
insert into school (candidate_id, s_name, degree) values (478, 'ridiculus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (650, 'pellentesque quisque porta', 'Associate');
insert into school (candidate_id, s_name, degree) values (590, 'eu magna', 'Graduate');
insert into school (candidate_id, s_name, degree) values (443, 'id', 'Transfer');
insert into school (candidate_id, s_name, degree) values (356, 'natoque penatibus et magnis', 'Master');
insert into school (candidate_id, s_name, degree) values (556, 'nulla justo aliquam quis', 'Associate');
insert into school (candidate_id, s_name, degree) values (515, 'arcu sed', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (488, 'nisi eu orci', 'Specialist');
insert into school (candidate_id, s_name, degree) values (595, 'ipsum', 'Master');
insert into school (candidate_id, s_name, degree) values (363, 'in imperdiet', 'Professional');
insert into school (candidate_id, s_name, degree) values (462, 'accumsan tellus nisi eu', 'Associate');
insert into school (candidate_id, s_name, degree) values (482, 'nulla pede ullamcorper augue', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (461, 'adipiscing molestie hendrerit at', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (568, 'sit amet', 'Specialist');
insert into school (candidate_id, s_name, degree) values (430, 'vivamus', 'Transfer');
insert into school (candidate_id, s_name, degree) values (359, 'diam cras pellentesque', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (375, 'nunc viverra dapibus nulla', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (574, 'elit', 'Professional');
insert into school (candidate_id, s_name, degree) values (641, 'vel accumsan tellus nisi', 'Master');
insert into school (candidate_id, s_name, degree) values (344, 'ipsum primis in faucibus', 'Master');
insert into school (candidate_id, s_name, degree) values (359, 'sit amet sapien', 'Professional');
insert into school (candidate_id, s_name, degree) values (549, 'duis', 'Associate');
insert into school (candidate_id, s_name, degree) values (344, 'eros', 'Specialist');
insert into school (candidate_id, s_name, degree) values (539, 'gravida', 'Master');
insert into school (candidate_id, s_name, degree) values (555, 'nulla suspendisse potenti cras', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (635, 'non mi integer', 'Associate');
insert into school (candidate_id, s_name, degree) values (524, 'nascetur ridiculus mus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (578, 'non quam nec dui', 'Graduate');
insert into school (candidate_id, s_name, degree) values (504, 'odio cras mi pede', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (419, 'sem', 'Specialist');
insert into school (candidate_id, s_name, degree) values (635, 'nunc vestibulum ante', 'Professional');
insert into school (candidate_id, s_name, degree) values (532, 'sed sagittis nam', 'Graduate');
insert into school (candidate_id, s_name, degree) values (357, 'et ultrices', 'Master');
insert into school (candidate_id, s_name, degree) values (424, 'erat volutpat in congue', 'Master');
insert into school (candidate_id, s_name, degree) values (397, 'vel sem sed sagittis', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (635, 'etiam justo etiam pretium', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (534, 'massa id lobortis convallis', 'Professional');
insert into school (candidate_id, s_name, degree) values (597, 'nonummy maecenas tincidunt', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (418, 'in faucibus', 'Transfer');
insert into school (candidate_id, s_name, degree) values (380, 'donec quis orci', 'Master');
insert into school (candidate_id, s_name, degree) values (474, 'massa donec dapibus duis', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (472, 'pretium', 'Specialist');
insert into school (candidate_id, s_name, degree) values (367, 'porttitor', 'Professional');
insert into school (candidate_id, s_name, degree) values (430, 'et', 'Associate');
insert into school (candidate_id, s_name, degree) values (572, 'interdum eu tincidunt', 'Professional');
insert into school (candidate_id, s_name, degree) values (511, 'dolor', 'Transfer');
insert into school (candidate_id, s_name, degree) values (442, 'donec', 'Graduate');
insert into school (candidate_id, s_name, degree) values (573, 'orci luctus et', 'Specialist');
insert into school (candidate_id, s_name, degree) values (665, 'mi', 'Professional');
insert into school (candidate_id, s_name, degree) values (500, 'nunc purus phasellus in', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (454, 'donec quis orci', 'Transfer');
insert into school (candidate_id, s_name, degree) values (607, 'arcu libero rutrum', 'Transfer');
insert into school (candidate_id, s_name, degree) values (463, 'et eros vestibulum', 'Professional');
insert into school (candidate_id, s_name, degree) values (590, 'maecenas tincidunt lacus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (460, 'a feugiat et', 'Graduate');
insert into school (candidate_id, s_name, degree) values (547, 'in hac habitasse platea', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (344, 'donec dapibus duis at', 'Graduate');
insert into school (candidate_id, s_name, degree) values (517, 'eget tincidunt eget tempus', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (499, 'pede libero quis', 'Professional');
insert into school (candidate_id, s_name, degree) values (559, 'nunc donec quis', 'Transfer');
insert into school (candidate_id, s_name, degree) values (444, 'enim blandit', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (562, 'orci luctus et ultrices', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (620, 'lobortis', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (404, 'nascetur ridiculus mus', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (403, 'amet', 'Associate');
insert into school (candidate_id, s_name, degree) values (596, 'sollicitudin', 'Master');
insert into school (candidate_id, s_name, degree) values (599, 'interdum eu', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (461, 'malesuada', 'Specialist');
insert into school (candidate_id, s_name, degree) values (554, 'orci', 'Transfer');
insert into school (candidate_id, s_name, degree) values (665, 'varius', 'Master');
insert into school (candidate_id, s_name, degree) values (650, 'vestibulum ac', 'Associate');
insert into school (candidate_id, s_name, degree) values (545, 'vel', 'Transfer');
insert into school (candidate_id, s_name, degree) values (400, 'rutrum nulla', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (615, 'justo eu massa donec', 'Professional');
insert into school (candidate_id, s_name, degree) values (334, 'vestibulum sagittis sapien cum', 'Specialist');
insert into school (candidate_id, s_name, degree) values (440, 'aliquet ultrices erat', 'Professional');
insert into school (candidate_id, s_name, degree) values (342, 'libero', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (433, 'dis parturient montes nascetur', 'Professional');
insert into school (candidate_id, s_name, degree) values (519, 'quam a', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (475, 'odio odio', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (595, 'sem duis aliquam', 'Master');
insert into school (candidate_id, s_name, degree) values (422, 'vel augue vestibulum rutrum', 'Graduate');
insert into school (candidate_id, s_name, degree) values (547, 'ac nulla sed vel', 'Associate');
insert into school (candidate_id, s_name, degree) values (389, 'sed accumsan', 'Master');
insert into school (candidate_id, s_name, degree) values (542, 'nec', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (351, 'quis lectus suspendisse', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (634, 'pellentesque volutpat dui maecenas', 'Associate');
insert into school (candidate_id, s_name, degree) values (357, 'in faucibus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (544, 'congue diam id ornare', 'Associate');
insert into school (candidate_id, s_name, degree) values (348, 'nulla justo aliquam quis', 'Specialist');
insert into school (candidate_id, s_name, degree) values (484, 'cubilia', 'Specialist');
insert into school (candidate_id, s_name, degree) values (349, 'amet diam in', 'Associate');
insert into school (candidate_id, s_name, degree) values (369, 'est quam pharetra', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (503, 'sapien iaculis', 'Master');
insert into school (candidate_id, s_name, degree) values (466, 'volutpat erat quisque', 'Graduate');
insert into school (candidate_id, s_name, degree) values (466, 'penatibus', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (515, 'consequat dui nec', 'Associate');
insert into school (candidate_id, s_name, degree) values (355, 'tincidunt ante vel', 'Graduate');
insert into school (candidate_id, s_name, degree) values (497, 'curabitur', 'Associate');
insert into school (candidate_id, s_name, degree) values (600, 'tristique in', 'Transfer');
insert into school (candidate_id, s_name, degree) values (647, 'mattis', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (344, 'eget', 'Associate');
insert into school (candidate_id, s_name, degree) values (399, 'vestibulum sagittis', 'Associate');
insert into school (candidate_id, s_name, degree) values (542, 'non', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (426, 'dictumst aliquam augue', 'Specialist');
insert into school (candidate_id, s_name, degree) values (563, 'turpis nec', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (429, 'pede justo', 'Professional');
insert into school (candidate_id, s_name, degree) values (392, 'ultrices mattis odio', 'Master');
insert into school (candidate_id, s_name, degree) values (650, 'justo sollicitudin ut', 'Graduate');
insert into school (candidate_id, s_name, degree) values (542, 'curabitur at', 'Transfer');
insert into school (candidate_id, s_name, degree) values (576, 'congue etiam justo', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (629, 'magna', 'Master');
insert into school (candidate_id, s_name, degree) values (449, 'bibendum morbi non', 'Bachelor');
insert into school (candidate_id, s_name, degree) values (515, 'felis ut', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (419, 'faucibus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (468, 'in', 'Associate');
insert into school (candidate_id, s_name, degree) values (572, 'eu tincidunt', 'Graduate');
insert into school (candidate_id, s_name, degree) values (433, 'congue elementum', 'Associate');
insert into school (candidate_id, s_name, degree) values (462, 'lectus pellentesque eget nunc', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (524, 'at velit eu', 'Specialist');
insert into school (candidate_id, s_name, degree) values (374, 'in', 'Graduate');
insert into school (candidate_id, s_name, degree) values (660, 'vivamus', 'Graduate');
insert into school (candidate_id, s_name, degree) values (578, 'sapien quis libero', 'Master');
insert into school (candidate_id, s_name, degree) values (656, 'in', 'Professional');
insert into school (candidate_id, s_name, degree) values (463, 'sodales scelerisque', 'Master');
insert into school (candidate_id, s_name, degree) values (408, 'suscipit a', 'Professional');
insert into school (candidate_id, s_name, degree) values (484, 'feugiat non', 'Master');
insert into school (candidate_id, s_name, degree) values (631, 'pede malesuada', 'Specialist');
insert into school (candidate_id, s_name, degree) values (570, 'justo sit amet sapien', 'Specialist');
insert into school (candidate_id, s_name, degree) values (344, 'cras mi pede malesuada', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (484, 'nibh in', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (656, 'amet', 'Master');
insert into school (candidate_id, s_name, degree) values (454, 'aliquam non mauris morbi', 'Graduate');
insert into school (candidate_id, s_name, degree) values (345, 'parturient', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (534, 'tincidunt in leo maecenas', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (372, 'vel augue vestibulum', 'Transfer');
insert into school (candidate_id, s_name, degree) values (652, 'sollicitudin ut', 'Undergraduate');
insert into school (candidate_id, s_name, degree) values (577, 'tellus nulla', 'Doctoral');
insert into school (candidate_id, s_name, degree) values (486, 'in', 'Bachelor');
